### PR TITLE
Roll Coin

### PR DESCRIPTION
**Pull request by tdk333**

### CODE REVIEW

**Review by dbuarque — CHANGES_REQUESTED** [review]
json is invalid

**Comment by tdk333** [comment]
I will fix it

**Comment by tdk333** [comment]
let me know if it is good now thanks

**Comment by tdk333** [comment]
???

**Comment by dbuarque** [comment]
json still invalid

**Comment by tdk333** [comment]
Hmm my dev does not even know what is the issue, can you please be more specific than just saying it is invalid? how can it be fixed to be valid?

**Comment by dbuarque** [comment]
You need to validate your json before send.

**Pull request closed without merging**
